import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header/Header";
import Navbar from "@/components/Navbar/Navbar";
import Hero from "@/components/Hero/Hero";
import Details from "@/components/Details/Details";
import Story from "@/components/Story/Story";
import Testimonials from "@/components/Testimonials/Testimonials";
import Parallax from "@/components/Parallax/Parallax";
import Offers from "@/components/Offers/Offers";
import Menu from "@/components/Menu/Menu";
import Services from "@/components/Services/Services";
import Blog from "@/components/Blog/Blog";
import Reservation from "@/components/Reservation/Reservation";
import Footer from "@/components/Footer/Footer";
import Dishes from "@/components/Dishes/Dishes";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>TastEat</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Navbar />
        <Hero />
        <Details />
        <Story />
        <Dishes />
        <Testimonials />
        <Parallax />
        <Offers />
        <Menu />
        <Services />
        <Blog />
        <Reservation />
        <Footer />
      </main>
    </>
  );
}
